# Generated by Django 4.2.21 on 2025-05-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=7, null=True
            ),
        ),
    ]
