# Generated by Django 4.2.21 on 2025-05-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_menuitem_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["category", "title"]},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="menuitem",
            old_name="name",
            new_name="title",
        ),
    ]
