# Generated by Django 4.2.21 on 2025-05-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_menuitem_options_rename_name_category_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "کتگوری", "verbose_name_plural": "گتگوری ها"},
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="menu_items/", verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="menu.category",
                verbose_name="گروه",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=155, unique=True, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.category",
                verbose_name="کتگوری",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="menu_items/", verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="موجود"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=7,
                null=True,
                verbose_name="قیمت",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=155, verbose_name="نام غذا"),
        ),
    ]
