# Generated by Django 4.2.21 on 2025-05-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_category_options_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["category", "title"],
                "verbose_name": "نام آیتم",
                "verbose_name_plural": "آیتم ها",
            },
        ),
    ]
